NinthDesertDude/Dynamic-Draw

Gui/BrushFactoryWindow.cs, PersistentSettings.cs
Changed the file extension comparisons in FilesInDirectory to use
OrdinalIgnoreCase.
Changed the loadedBrushPaths field to a HashSet<string> with
StringComparer.OrdinalIgnoreCase as the equality comparer.
Changed the CustomBrushLocations property to a HashSet<string>.
=> Use case-insensitive path and filename comparisons

Gui/BrushFactoryWindow.cs
This fixes the issue welshblue reported with only the last folder in the list being loaded.
https://forums.getpaint.net/topic/113361-whats-next-for-brush-factory/?do=findComment&comment=550283
=> Handle \r\n and \r when splitting the custom brush directory string

Gui/BrushFactoryWindow.cs
Changed the directory searching to use EnumerateFiles instead of
storing the files in a list.
This allows non-image files to be excluded without waiting for the
entire directory to be processed.
One consequence of this change is that invalid or non-directory paths
are ignored instead of being processed as a potential image file.
=> Improve performance when searching directories

BrushFactory.csproj, Gui/BrushFactoryWindow.cs, Interop/SafeNativeMethods.cs
Use P/Invoke to call the Win32 GetKeyState API.
This removes the dependency on the System.Windows.Input.Keyboard class
in PresentationCore.
=> Remove the PresentationCore dependency

Abr/AbrBrush.cs, Abr/AbrBrushCollection.cs, Abr/AbrReader.cs, Abr/Internal/BigEndianBinaryReader.cs, Abr/Internal/BrushSectionParser.cs, Abr/Internal/RLEHelper.cs, Abr/Internal/SampledBrush.cs, Abr/Internal/SampledBrushCollection.cs, BrushFactory.csproj, Globalization/GlobalStrings.Designer.cs, Globalization/GlobalStrings.resx, Gui/BrushFactoryWindow.cs
This removes the need for users to convert Photoshop-compatible brushes
to another image format before use.
=> Add support for loading ABR files

BrushFactory.csproj, Gui/BrushFactoryWindow.cs, TempDirectory.cs
This prevents the undo history from being lost if the user's temp
folder is emptied when the dialog is open.
It also allows the files to be deleted when the dialog is closed.
=> Move the undo history into a temporary directory

BrushFactoryEffect.cs, Gui/BrushFactoryWindow.cs, RenderSettings.cs
This reduces the amount of code required to render the final image to the destination surface and should also improve performance.
=> Store the final image as a Paint.NET Surface

Utils.cs
The code added in https://github.com/JoshuaLamusga/Brush-Factory/commit/6b1be929354572fb45a9dec1ca4f98abb645be29
produces incorrect dimensions when scaling images.
This causes any image that is down-scaled to be displayed as a blank
spot in the brush list.
=> Fix the image scaling code in ComputeBrushSize

Gui/BrushFactoryPreferences.Designer.cs, Gui/BrushFactoryPreferences.cs, Gui/BrushFactoryWindow.cs
MSDN recommends that derived classes should override the virtual On*
methods in place of adding event handlers.
=> Override the On* methods instead of using event handlers

Gui/BrushFactoryWindow.cs
It is not necessary to create an instance of the RenderArgs class to
get the EffectSourceSurface size or alias it to a temporary Bitmap.
=> Do not create unnecessary RenderArgs instances

Gui/BrushFactorySettings.cs
Using FileMode.OpenOrCreate can leave fragments of the previous XML
data at the end of the file.
This will cause the DataContractSerializer to return an error when it
tries to read the saved file.
=> Use FileMode.Create when writing the settings

Gui/BrushFactoryWindow.cs
Update the ListView virtual item count after adding the default brushes to the list of loaded brushes.
Corrected an issue that prevented the default brushes from being loaded first in the list.
Fixed a bug that prevented the user's previously selected brush from being selected in the ListView.
=> Fix the default brush loading

Gui/BrushFactoryWindow.cs
This fixes a regression with the brush list being duplicated when the
user clears the custom brushes in the UI.
=> Clear the loaded brushes in InitBrushes

Gui/BrushFactoryWindow.cs
This would occur if the user start drawing before brushes are loaded.
=> Fix a null reference crash in DrawBrush

Gui/BrushFactoryWindow.cs
Check if the displayCanvasBG field has been disposed before calling its
PointToClient method.
=> Fix an object disposed crash in RepositionUpdate_Tick

Gui/BrushFactoryWindow.cs, Utils.cs
This removes the need to alias the EffectSourceSurface to a temporary
bitmap.
=> Add a CreateBitmapFromSurface method to the Utils class

Gui/BrushFactoryWindow.cs
Set the dialog size based on the working area of the monitor that the
dialog is being displayed on instead of always using the primary
monitor size.
=> Improve support for multiple monitors

Abr/AbrBrush.cs, Abr/AbrReader.cs, Gui/BrushFactoryWindow.cs, Utils.cs
Drawing all images using the 32PArgb pixels format fixes the various bugs that GDI+ exhibits with drawing 32Argb images with transparency.
It may also improve the performance of various GDI+ methods.
Resolves #1.
=>  Use pre-multiplied alpha when drawing images

Gui/BrushFactoryWindow.cs
This causes zoom to happen at a specific point, instead of the dead center of the canvas.
It can be one of two points:
- The center of the viewport --- if using the slider control
- The mouse cursor location --- if using the mouse wheel
=> Zoom at point; not dead center

Gui/BrushFactoryWindow.cs
Paint.net can return null for userFilesService.UserFilesPath. If so, guess at the usual path. If the path doesn't exist, throw an error and skip loading the settings. Moved the relevant code into the try block to avoid future crashes.
=> Fix null error with userFilesService from PDN

Gui/BrushFactoryWindow.cs
Fix "Use clipboard as background" having input image being scaled by DPI-aware value which causes incorrect sizing compared to canvas size.
`Graphics#DrawImage(Image image, int x, int y)` will use the DPI value of the target device to scale the drawn image unless the image size is specified directly (see `Graphics#DrawImage(Image image, int x, int y, int width, int height)` overload). This is problematic because Paint.NET canvas and Brush Factory's canvas are not scaled by the device DPI. This change fixes this issue by using the stated overload, using the background canvas' width and height.
=> Fix "Use clipboard as background" incorrect image size

Gui/BrushFactoryWindow.cs
Fixes forward compatibility with .NET 5.
=> Replace uses of ContextMenu with ContextMenuStrip

BrushSettings.cs, Gui/DynamicDrawWindow.cs, Utils.cs
The Jagged smoothing option wasn't jagged with rotation. It turns out GDI+ also has no way of creating aliased rotations. All that is, is rounding each alpha to 0 or 255 (accounting for premultiplication) before drawing the pixel; this is now done with AliasImage() as a separate step in the RotateImage() function for Jagged smoothing. Since lockbits is forcibly used whenever jagged smoothing is set, RotateImage will always be called and this should work with any combination of blend mode, overwrite mode, transforms like rotate, etc. It's slightly slower to use lockbits and a little slower yet to loop twice through the image (this could be improved), but it seems fast enough.
The result is that when Jagged smoothing is on, all brushes are drawn with aliasing, even if the brush didn't have …
=> Update the Jagged smoothing to force aliasing with any brush

Abr/Internal/BrushSectionParser.cs
Some files were being rejected due to having a descriptor section length that is too short.
=> Fix a bug when parsing newer brushes
